name: Bake time

on:
  pull_request:
    types:
      - opened
      - synchronize
  workflow_dispatch:
  schedule:
    - cron: "0 */1 * * *" # Runs every 1 hour

jobs:
  baking_pull_request:
    name: "Baking pull request..."
    runs-on: ubuntu-latest
    env:
      SLEEP_HOURS: 3 # Max GHA runner time is 6 hours 
    steps:
      - name: Sleep to enforce bake time
        run: |
          echo "Sleeping for configured bake time of ${{ env.SLEEP_HOURS }} hours..."
          sleep $(( ${{ env.SLEEP_HOURS }} * 3600 ))
      - name: Bake complete
        run: echo "Bake time completed successfully."
