name: Link Checker
on: [push, pull_request]

jobs:
  linkchecker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Lychee Link Checker
        id: lychee
        uses: lycheeverse/lychee-action@master
        with:
          args: --accept=200,403,429 "./**/*.md" "./**/*.txt"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Fail on Error
        run: exit ${{ steps.lychee.outputs.exit_code }}
